version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: Build Docker image
          command: docker build -t scholzj/circleci-centos-java:circle .
      - deploy:
          name: Tag docker images
          command: |
            docker tag scholzj/circleci-centos-java:circle docker.io/scholzj/circleci-centos-java:centos7-java17
            docker tag scholzj/circleci-centos-java:circle docker.io/scholzj/circleci-centos-java:latest-java17
            docker tag scholzj/circleci-centos-java:circle docker.io/scholzj/circleci-centos-java:latest
      - deploy:
          name: Push docker images
          command: |
            docker push scholzj/circleci-centos-java:centos7-java17
            docker push scholzj/circleci-centos-java:latest-java17
            docker push scholzj/circleci-centos-java:latest
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
            context: org-global
